---
title: "Capstone backend 8"
categories:
  -  Capstone
tags:
  -  JavsScript
  -  React
---
개발일지 이번에 한것
------
react redirection 토큰이 없는점 확인

리다이렉션시 토큰이 바로 없는것은 홈에서는 문제가 안돼지만 다른 페이지에서는 access 토큰이 없는체로 axios요청을 보내서 에러가 발생한다. 해결 방법은 동기로 처리하거나 페이지마다 처리해줘야 됬다.

그래서 여러가지 시도를 했지만 동기로 request 처리하는 api는 쿠키를 보내지않거나 잘 사용되지가 않았고 직접 처리하는건 수십개의 페이지를 처리해야된다 생각해 별로라 생각했다.

그러는 와중 axios로 interceptor로 이를 해결하신 분이 있어서 이분걸 응용하기로 했다.

[링크](https://maruzzing.github.io/study/rnative/axios-interceptors%EB%A1%9C-%ED%86%A0%ED%81%B0-%EB%A6%AC%ED%94%84%EB%A0%88%EC%8B%9C-%ED%95%98%EA%B8%B0/)

axios interceptor란 axios로 요청을 보내거나 결과를 받을때 request 나 response를 가로채 내가 이용할 특정 로직을 추가하는것이다.

나는 이 코드를 프로젝트에 _app.js에 추가하였다. 그이유는 next.js는 _app.js를 공통모듈로 모든 다른 모듈에 적용시키기 때문

```javascript
import "../styles/scss/style.scss";
import Layout from "../layout/Layout";
import axios from "axios";
import cookie from 'react-cookies';
import cookies from "next-cookies";


const coa = cookie.loadAll();
const allCookies = cookies(coa);
const refreshTokenByCookie = allCookies['refreshToken'];//쿠키값 받아오기 
axios.defaults.withCredentials = true;

let isTokenRefreshing = false;//토큰 리프레싱 했는지
let refreshSubscribers = [];//리프레시 토큰 보낼때 나머지 axios요청처리할 함수들 배열 

const onTokenRefreshed = (accessToken) => {//배열에 있는 axios요청 실행하는 함수 

  refreshSubscribers.map((callback) => callback(accessToken));
};

const addRefreshSubscriber = (callback) => {//배열에 axios 요청 추가하는 함수 
  refreshSubscribers.push(callback);
};

axios.interceptors.response.use(
  (response) => {
    // axios.interceptors.response.eject();
    return response;
  },
  async (error) => {
    const {
      config,
      response: { status },
    } = error;
    const originalRequest = config;
    if (status === 401) {
      if (!isTokenRefreshing&&refreshTokenByCookie!=undefined) {
        // isTokenRefreshing이 false인 경우에만 token refresh 요청
        isTokenRefreshing = true;
        setTimeout(async ()=>{
          const { headers } = await axios.get(
            `http://localhost:8080/sportsmate/member/public/reissue`);// token refresh api
          // 새로운 토큰 저장
          const accessToken = headers.authorization;
          axios.defaults.headers.common['Authorization'] = accessToken;
          // 새로운 토큰으로 지연되었던 요청 진행
          onTokenRefreshed(accessToken);
        },0);
        
      }
      // token이 재발급 되는 동안의 요청은 refreshSubscribers에 저장
      const retryOriginalRequest = new Promise((resolve) => {
         addRefreshSubscriber((accessToken) => {
           resolve(axios(originalRequest));
        })ㄴ
      })
      return retryOriginalRequest;
    }
    return Promise.reject(error);
  }
);


let MyApp =  ({ Component, pageProps })=>(
    <Layout>
      <Component {...pageProps} />
    </Layout>
  );


export default MyApp;
```
여기서는 response를 interceptor를 활용한다.

내용은 다음과 같다. 만약 이사이트 방문이 처음이어서 혹은 redirection을해서 accesstoken이 없을때 401 에러가 뜨는데 이를 interceptor를 해서 reissue를 보내는 것이다.

addRefreshSubscriber는 기존의 axios요청의 config를 활용해 다시 요청을 보내는것을 promise로 refreshSubscribers 배열에 추가하게 구현하였고 onTokenRefreshed를 통해 이를 배열에서 꺼내 resolve하게 하였다.

그외에 isTokenRefreshing같은 경우엔 만약 reissue를 보내는데 또 axios요청이 생겨 또 reissue를 보내는것을 방지하려고 추가하였다.

즉 메커니즘은 axios로 요청을 보낼때 accesstoken이 없어 401에러가 뜰때 이를 interceptor로 가로채 reissue요청을 보내게하고 그때 보내는 axios요청을 배열에 담아두고 reissue가 성공적으로 이루어질때 요청을 다시 보내 정상적인 결과를 받게한다.

여기서 setTimeout을 사용한 이유는 addRefreshSubscriber를 하기전에 onTokenRefreshed(accessToken);을 먼저 실행해 정상적인 처리가 안되기 때문이다. 

이결과가 어떻게 성공할까에대한 의문이 들수있는 기본적으로 Resolve를 안한 promise는 pending으로 이때 then을 실행되지 않는다.

```javascript
const retryOriginalRequest = new Promise((resolve) => {
         addRefreshSubscriber((accessToken) => {
           resolve(axios(originalRequest));
        });
      })
```
이 부분을 보면 promise의 resolve를 콜백으로 나중에 처리한다. 즉 onTokenRefreshed(accessToken);을 실행해야 resolve가 되므로 then이 작동하지 않는다.

```javascript
const [my, setMy] = useState({});
  console.log(axios.defaults.headers.common['Authorization']);

  useEffect(() => {
    axios.get(`http://localhost:8080/sportsmate/member/my`)
      .then(function (response) {
          setMy(response.data);
      })
      .catch(function (error) {
        console.log("에러입니뎅");
      });
  }, []);
```
즉 이런식으로 데이터를 받는다해도 then은 나중에 처리되므로 정상적으로 처리가 될것이다.

이를 통해 redirection버그를 해결했다 후우~





